---
- name: Check if rustup is installed
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.cargo/bin/rustup"
  register: user_rustup_stat
  become: false
  tags: ["rust", "cargo", "base"]

- name: Install rustup
  when: not user_rustup_stat.stat.exists
  become: false
  tags: ["rust", "cargo", "base"]
  block:
    - name: Create a temporary file for the rustup-init script
      ansible.builtin.tempfile:
        state: file
        suffix: -rustup-init.sh
      register: user_rustup_script

    - name: Download rustup-init script
      ansible.builtin.get_url:
        url: https://sh.rustup.rs
        dest: "{{ user_rustup_script.path }}"
        mode: "0755"
        force: true

    - name: Run rustup-init
      ansible.builtin.command:
        cmd: "{{ user_rustup_script.path }} -y"
        creates: "{{ ansible_user_dir }}/.cargo/bin/rustup"

  always:
    - name: Clean up rustup-init script
      ansible.builtin.file:
        path: "{{ user_rustup_script.path }}"
        state: absent
      when: user_rustup_script.path is defined

- name: Install cargo packages
  tags: ["cargo", "base"]
  when: user_install_cargo_packages | bool
  become: false
  environment:
    PATH: "{{ ansible_user_dir }}/.cargo/bin:{{ ansible_user_dir }}/.local/bin:{{ ansible_env.PATH }}:/sbin:/bin"
  block:
    - name: Set cargo jobs to 4
      ansible.builtin.copy:
        content: |
          [build]
          jobs = 4
        dest: "{{ ansible_user_dir }}/.cargo/config.toml"
        mode: "0644"
        backup: true

    - name: List installed cargo crates
      ansible.builtin.command: cargo install --list
      register: user_cargo_installed
      changed_when: false
      failed_when: false
      check_mode: false

    - name: Work out which cargo crates are missing
      ansible.builtin.set_fact:
        user_cargo_missing: >-
          {{ user_cargo_packages | difference(
               user_cargo_installed.stdout_lines
               | select('match', '^[^ ]')
               | map('split', ' ')
               | map('first')
               | list) }}

    - name: Install missing cargo packages
      community.general.cargo:
        name: "{{ item }}"
        state: present
        locked: true
      loop: "{{ user_cargo_missing }}"
