---
all:
  hosts:
    tinybot:
      ansible_host: 192.168.41.11
    gir:
      ansible_host: 192.168.41.10
    soundbot:
      ansible_host: 192.168.41.13
  children:
    workstations:
      hosts:
        tinybot:
        gir:
        soundbot:
    osbuild_targets:
      hosts:
        tinybot:
