id = "rpmfusion-nonfree-updates"
name = "RPM Fusion Nonfree Updates for EL 10"
type = "yum-baseurl"
url = "http://download1.rpmfusion.org/nonfree/el/updates/10/x86_64/"
check_gpg = true
check_ssl = true
gpgkey_urls = ["file:///usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-nonfree-el-10"]
