FROM {{ container_base_image }}
RUN dnf -y install {{ container_bootstrap_packages }} && dnf clean all \
 && useradd -m molecule \
 && echo 'molecule ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/molecule
CMD ["/sbin/init"]
