id = "fedora"
name = "Fedora 43 - x86_64"
type = "yum-metalink"
url = "https://mirrors.fedoraproject.org/metalink?repo=fedora-43&arch=x86_64"
check_gpg = false
check_ssl = true
check_repogpg = false
system = false