id = "fedora-nvidia-lts"
name = "negativo17 - Nvidia"
type = "yum-baseurl"
url = "https://negativo17.org/repos/nvidia-580/fedora-43/x86_64/"
check_gpg = true
check_ssl = true
check_repogpg = false
system = false