id = "rpmfusion-free"
name = "RPM Fusion Free for Fedora 43"
type = "yum-metalink"
url = "https://mirrors.rpmfusion.org/metalink?repo=free-fedora-43&arch=x86_64"
check_gpg = true
check_ssl = true
gpgkey_urls = ["https://us.mirrors.cicku.me/rpmfusion/free/fedora/RPM-GPG-KEY-rpmfusion-free-fedora-2020"]
