#!/usr/bin/env python3
import csv
import os
import sys

from ruamel.yaml import YAML


def main():
    yaml = YAML()
    yaml.preserve_quotes = True

    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)

    csv_path = os.path.join(project_root, "files", "project_names_descriptions.csv")
    dist_map_path = os.path.join(project_root, "vars", "packages", "00-distributions.yml")
    fedora_path = os.path.join(project_root, "vars", "packages", "Fedora.yml")
    alma_path = os.path.join(project_root, "vars", "packages", "AlmaLinux.yml")

    # Read mappings
    with open(dist_map_path, "r") as f:
        dist_map = yaml.load(f)
    package_mappings = dist_map.get("package_mappings", {})

    fedora_packages = {}
    alma_packages = {}

    with open(csv_path, "r") as f:
        reader = csv.reader(f)
        header = next(reader)
        for row in reader:
            if not row or row[0].startswith("#"):
                continue
            if len(row) >= 4:
                pkg, category, subcat, desc = (
                    row[0].strip(),
                    row[1].strip(),
                    row[2].strip(),
                    row[3].strip(),
                )

                # Map for Fedora
                f_pkg = package_mappings.get(pkg, {}).get("fedora", pkg)
                fedora_packages.setdefault(category, {}).setdefault(subcat, []).append(f_pkg)

                # Map for AlmaLinux
                a_pkg = package_mappings.get(pkg, {}).get("almalinux", pkg)
                alma_packages.setdefault(category, {}).setdefault(subcat, []).append(a_pkg)

    def update_yaml(file_path, package_dict):
        with open(file_path, "r") as f:
            data = yaml.load(f)

        data["system_packages"] = package_dict

        with open(file_path, "w") as f:
            f.write("# AUTO-GENERATED from files/project_names_descriptions.csv\n")
            f.write("# Do not edit this file directly. Edit the CSV and run:\n")
            f.write("#   python scripts/csv_to_packages.py\n")
            yaml.dump(data, f)

    update_yaml(fedora_path, fedora_packages)
    update_yaml(alma_path, alma_packages)
    print("Successfully generated vars/packages/Fedora.yml and vars/packages/AlmaLinux.yml")


if __name__ == "__main__":
    main()
