#!/usr/bin/env python3
"""Generate per-distribution package taxonomy files from the project CSV.

Reads files/project_names_descriptions.csv, maps package names per
distribution through the package_mappings in vars/packages/00-distributions.yml,
and writes vars/packages/{Fedora,AlmaLinux,Rocky}.yml.

Idempotent: running the generator twice produces byte-identical files. Each
generated file carries the AUTO-GENERATED header exactly once; a distro file
that already exists keeps its hand-curated preamble and section comments
(ruamel round-trip mode preserves them).
"""

import csv
import os

from ruamel.yaml import YAML
from ruamel.yaml.comments import CommentedMap

# Distributions modeled by the pipeline: {Ansible distribution: mapping key
# in vars/packages/00-distributions.yml package_mappings}.
DISTROS = {
    "Fedora": "fedora",
    "AlmaLinux": "almalinux",
    "Rocky": "rocky",
}

HEADER = (
    "# AUTO-GENERATED from files/project_names_descriptions.csv\n"
    "# Do not edit this file directly. Edit the CSV and run:\n"
    "#   python scripts/csv_to_packages.py\n"
)

# Preamble written for a distro file that does not exist yet. Existing files
# keep whatever preamble they carry (round-tripped by ruamel).
PREAMBLES = {
    "Rocky": (
        "# System Package Taxonomy for Rocky Linux\n"
        "# Collection-level package definitions for immutable bootc images\n"
        "# Used by roles: osbuild, audio, sway, workstation, tools, etc.\n"
        "#\n"
        "# NOTE: Package names were verified against live Rocky Linux 9/10\n"
        "# BaseOS, AppStream, CRB, and EPEL 9/10 repositories (2026-10-01);\n"
        "# multimedia entries resolve against RPM Fusion EL updates-only\n"
        "# channels (same availability as AlmaLinux). Rocky aliases the EL\n"
        "# package names via the `rocky:` keys in 00-distributions.yml.\n"
    ),
}


def read_packages(csv_path, package_mappings):
    """Flatten the CSV into {distro: {category: {subcategory: [names]}}}."""
    distro_packages = {distro: {} for distro in DISTROS}

    with open(csv_path, "r") as f:
        reader = csv.reader(f)
        next(reader)  # header row
        for row in reader:
            if not row or row[0].startswith("#"):
                continue
            if len(row) >= 4:
                pkg, category, subcat = (row[i].strip() for i in range(3))
                for distro, map_key in DISTROS.items():
                    mapped = package_mappings.get(pkg, {}).get(map_key, pkg)
                    distro_packages[distro].setdefault(category, {}).setdefault(subcat, [])
                    distro_packages[distro][category][subcat].append(mapped)

    return distro_packages


def write_taxonomy(file_path, package_dict, distro):
    """(Re)write one distro taxonomy file, header exactly once."""
    yaml = YAML()
    yaml.preserve_quotes = True
    yaml.indent(mapping=2, sequence=4, offset=2)

    preamble = ""
    if os.path.exists(file_path):
        with open(file_path, "r") as f:
            raw = f.read()
        # Strip the document marker and every previously generated header
        # block so repeated runs cannot accumulate copies.
        lines = raw.splitlines(keepends=True)
        while lines and lines[0].strip() == "---":
            lines.pop(0)
        header_lines = HEADER.splitlines(keepends=True)
        while lines[: len(header_lines)] == header_lines:
            lines = lines[len(header_lines) :]
        data = yaml.load("".join(lines)) or CommentedMap()
    else:
        preamble = PREAMBLES.get(distro, "")
        data = CommentedMap()

    data["system_packages"] = package_dict

    with open(file_path, "w") as f:
        f.write("---\n")
        f.write(HEADER)
        if preamble:
            f.write(preamble)
        yaml.dump(data, f)


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)

    csv_path = os.path.join(project_root, "files", "project_names_descriptions.csv")
    dist_map_path = os.path.join(project_root, "vars", "packages", "00-distributions.yml")

    yaml = YAML()
    yaml.preserve_quotes = True
    with open(dist_map_path, "r") as f:
        dist_map = yaml.load(f)
    package_mappings = dist_map.get("package_mappings", {})

    distro_packages = read_packages(csv_path, package_mappings)

    for distro, packages in distro_packages.items():
        file_path = os.path.join(project_root, "vars", "packages", distro + ".yml")
        write_taxonomy(file_path, packages, distro)
        print("Generated " + file_path)


if __name__ == "__main__":
    main()
