---
galaxy_info:
  author: b08x
  description: Provision a composer-cli workstation blueprint via osbuild-composer
  company: b08x
  license: GPL-2.0-or-later
  min_ansible_version: "2.15"
  platforms:
    - name: Fedora
      versions:
        - all
    - name: AlmaLinux
      versions:
        - "8"
        - "9"
        - "10"
    - name: EL
      versions:
        - "8"
        - "9"
        - "10"
  galaxy_tags:
    - osbuild
    - composer
    - composercli
    - image

dependencies: []
