# BaseOS per upstream osbuild/images rocky-9.json (verified 2026-10-01)
id = "rocky-baseos"
name = "Rocky Linux 9 - BaseOS"
type = "yum-baseurl"
url = "https://dl.rockylinux.org/pub/rocky/9/BaseOS/x86_64/os/"
check_gpg = true
check_ssl = true
gpgkey_urls = ["file:///usr/share/distribution-gpg-keys/rocky/RPM-GPG-KEY-Rocky-9"]
