# VS Code yum repo per code.visualstudio.com/docs/setup/linux (verified 2026-10-01)
id = "vscode"
name = "Visual Studio Code"
type = "yum-baseurl"
url = "https://packages.microsoft.com/yumrepos/vscode"
check_gpg = true
check_ssl = true
gpgkey_urls = ["file:///usr/share/distribution-gpg-keys/microsoft/microsoft.asc"]
