---
- name: System Provisioning and Base Configuration
  hosts: workstations
  become: true
  gather_facts: false
  pre_tasks:
    - name: Gather facts as unprivileged connection user
      ansible.builtin.setup:
      become: false
      tags: ["always"]

    # to allow for ansible pipelining functionality
    # https://docs.ansible.com/ansible/2.4/intro_configuration.html#pipelining
    # while this requirement was removed in RHEL, many other distros leave this option enabled
    - name: Disable requiretty for user so automation can run without interruption
      ansible.builtin.lineinfile:
        dest: /etc/sudoers
        regexp: "^Defaults    requiretty"
        line: "Defaults:{{ ansible_user_id }}    !requiretty"
        backrefs: false
        backup: false
        validate: "visudo -cf %s"
      when: ansible_user_id != 'root'
      tags: ["sudoers"]

    - name: Display ansible_distribution
      ansible.builtin.debug:
        msg: |
          The host {{ inventory_hostname }} has {{ ansible_distribution }} installed,
          which belongs to the {{ ansible_os_family }} OS family. Run as {{ ansible_user_id }}
      tags: ["always"]

    - name: Symlink /etc/os-release to /etc/system-release
      ansible.builtin.file:
        src: /etc/os-release
        dest: /etc/system-release
        state: link
  roles:
    - role: base
      tags: ["base", "system"]
