---
- name: User Workstation Setup
  hosts: workstations
  become: false
  gather_facts: false
  environment:
    PATH: "{{ workstation_path_dirs | join(':') }}:{{ ansible_env.PATH }}:/sbin:/bin"
  pre_tasks:
    - name: Gather facts as unprivileged connection user
      ansible.builtin.setup:
      tags: ["always"]
  roles:
    - role: b08x.devworkstation.user
      tags: ["user", "system"]
